apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-secret
  namespace: payment
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: database-secret

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: database-secret
        property: password
